# Generated by Django 4.1.7 on 2023-07-29 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emp_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=50)),
                ('emp_branch', models.CharField(max_length=50)),
                ('emp_phone', models.IntegerField(null=True)),
                ('emp_email', models.CharField(max_length=50)),
            ],
        ),
    ]
