# Generated by Django 4.1.7 on 2023-07-29 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askapp', '0002_emp_db'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emp_db',
            old_name='emp_phone',
            new_name='phone_num',
        ),
        migrations.RemoveField(
            model_name='emp_db',
            name='emp_branch',
        ),
        migrations.RemoveField(
            model_name='emp_db',
            name='emp_email',
        ),
        migrations.RemoveField(
            model_name='emp_db',
            name='emp_name',
        ),
        migrations.AddField(
            model_name='emp_db',
            name='e_mail',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='emp_db',
            name='first_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='emp_db',
            name='last_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='emp_db',
            name='message_query',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
