# Generated by Django 4.1.7 on 2023-07-30 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askapp', '0004_rename_emp_db_help_db'),
    ]

    operations = [
        migrations.AddField(
            model_name='help_db',
            name='resolve_query',
            field=models.BooleanField(default=False),
        ),
    ]
