# Generated by Django 4.1.7 on 2023-07-30 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askapp', '0005_help_db_resolve_query'),
    ]

    operations = [
        migrations.CreateModel(
            name='review_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('message', models.CharField(max_length=250, null=True)),
                ('star_rating', models.IntegerField(null=True)),
            ],
        ),
    ]
